name = "router-proxy-template"
version = "<%= package.version %>"
description = "Router template"

# `salt` here only affects proxy contract
[setting.salt]
description = "Change this to a unique string when deploying multiple instances of the system. Note that only the proxy contract will be unique."
defaultValue = "main"

[setting.owner]
description = "Admin user for the system"
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[run.deploy]
exec = "scripts/deploy.ts"
func = "deploy"
args = ["System", ".*"]
modified = ["contracts", "scripts"]
