[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/unit'
cache_path  = 'forge-cache'
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/tree/master/config